### ISSUE TITLE
Docs: docker run example has superflous "goreleaser" arg

### ISSUE THREAD

**Issue by neilotoole** [mailchain/goreleaser-xcgo#1]
I suspect the example to start the container (from `README.md` and also in the medium article) has a mistake. Running this:

```sh
docker run --rm --privileged \
  -v $PWD:/go/src/github.com/mailchain/mailchain \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -w /go/src/github.com/mailchain/mailchain \
  mailchain/goreleaser-xcgo goreleaser --snapshot --rm-dist
```

outputs:

```
57957ac2c49f: Pull complete 
4e487665a411: Pull complete 
Digest: sha256:ec1500c259a8d166b8a706190d0388edc80d80c2e5db28ea5c622332dd1a10f6
Status: Downloaded newer image for mailchain/goreleaser-xcgo:latest

goreleaser: error: unexpected goreleaser, try --help
```

The `goreleaser` arg on the last line probably shouldn't be there, as the `goreleaser` command will be invoked on container run via `entrypoint.sh`:

https://github.com/mailchain/goreleaser-xcgo/blob/ae66d85ebc18c1c614bb2322e9dcc48aa8d3932f/scripts/entrypoint.sh#L17

* Thanks for having put this image out there, saved me a lot of effort.

**Comment by robdefeo** [comment]
Thanks @neilotoole I have also updated the article. Glad this has been useful for you.
